AWSTemplateFormatVersion: "2010-09-09"

Description: ""

Parameters:
  S3Bucket:
    Type: String
    Default: ''
    Description: S3 BucketName

Resources:
    OrderLIAppFlow:
        Type: "AWS::AppFlow::Flow"
        Properties:
            FlowName: "OrderLineItem"
            SourceFlowConfig: 
                ConnectorType: "Salesforce"
                ConnectorProfileName: "<INSERT_VALUE>"
                SourceConnectorProperties: 
                    Salesforce: 
                        Object: "OrderItem"
                        EnableDynamicFieldUpdate: false
                        IncludeDeletedRecords: true
            DestinationFlowConfigList: 
              - 
                ConnectorType: "S3"
                DestinationConnectorProperties: 
                    S3: 
                        BucketName: !Ref S3Bucket
                        S3OutputFormatConfig: 
                            FileType: "CSV"
                            PrefixConfig: 
                                PrefixType: "PATH"
                                PrefixFormat: "DAY"
                            AggregationConfig: 
                                AggregationType: "None"
            TriggerConfig: 
                TriggerType: "OnDemand"
            Tasks: 
              - 
                SourceFields: 
                  - "IsDeleted"
                ConnectorOperator: 
                    Salesforce: "EQUAL_TO"
                TaskType: "Filter"
                TaskProperties: 
                  - 
                    Key: "DATA_TYPE"
                    Value: "boolean"
                  - 
                    Key: "VALUE"
                    Value: "True"
              - 
                SourceFields: 
                  - "Id"
                  - "Product2Id"
                  - "IsDeleted"
                  - "OrderId"
                  - "PricebookEntryId"
                  - "OriginalOrderItemId"
                  - "AvailableQuantity"
                  - "Quantity"
                  - "CurrencyIsoCode"
                  - "UnitPrice"
                  - "ListPrice"
                  - "TotalPrice"
                  - "Description"
                  - "CreatedDate"
                  - "CreatedById"
                  - "LastModifiedDate"
                  - "LastModifiedById"
                  - "SystemModstamp"
                  - "OrderItemNumber"
                ConnectorOperator: 
                    Salesforce: "PROJECTION"
                TaskType: "Filter"
              - 
                SourceFields: 
                  - "Id"
                ConnectorOperator: 
                    Salesforce: "NO_OP"
                DestinationField: "Id"
                TaskType: "Map"
                TaskProperties: 
                  - 
                    Key: "DESTINATION_DATA_TYPE"
                    Value: "id"
                  - 
                    Key: "SOURCE_DATA_TYPE"
                    Value: "id"
              - 
                SourceFields: 
                  - "Product2Id"
                ConnectorOperator: 
                    Salesforce: "NO_OP"
                DestinationField: "Product2Id"
                TaskType: "Map"
                TaskProperties: 
                  - 
                    Key: "DESTINATION_DATA_TYPE"
                    Value: "reference"
                  - 
                    Key: "SOURCE_DATA_TYPE"
                    Value: "reference"
              - 
                SourceFields: 
                  - "IsDeleted"
                ConnectorOperator: 
                    Salesforce: "NO_OP"
                DestinationField: "IsDeleted"
                TaskType: "Map"
                TaskProperties: 
                  - 
                    Key: "DESTINATION_DATA_TYPE"
                    Value: "boolean"
                  - 
                    Key: "SOURCE_DATA_TYPE"
                    Value: "boolean"
              - 
                SourceFields: 
                  - "OrderId"
                ConnectorOperator: 
                    Salesforce: "NO_OP"
                DestinationField: "OrderId"
                TaskType: "Map"
                TaskProperties: 
                  - 
                    Key: "DESTINATION_DATA_TYPE"
                    Value: "reference"
                  - 
                    Key: "SOURCE_DATA_TYPE"
                    Value: "reference"
              - 
                SourceFields: 
                  - "PricebookEntryId"
                ConnectorOperator: 
                    Salesforce: "NO_OP"
                DestinationField: "PricebookEntryId"
                TaskType: "Map"
                TaskProperties: 
                  - 
                    Key: "DESTINATION_DATA_TYPE"
                    Value: "reference"
                  - 
                    Key: "SOURCE_DATA_TYPE"
                    Value: "reference"
              - 
                SourceFields: 
                  - "OriginalOrderItemId"
                ConnectorOperator: 
                    Salesforce: "NO_OP"
                DestinationField: "OriginalOrderItemId"
                TaskType: "Map"
                TaskProperties: 
                  - 
                    Key: "DESTINATION_DATA_TYPE"
                    Value: "reference"
                  - 
                    Key: "SOURCE_DATA_TYPE"
                    Value: "reference"
              - 
                SourceFields: 
                  - "AvailableQuantity"
                ConnectorOperator: 
                    Salesforce: "NO_OP"
                DestinationField: "AvailableQuantity"
                TaskType: "Map"
                TaskProperties: 
                  - 
                    Key: "DESTINATION_DATA_TYPE"
                    Value: "double"
                  - 
                    Key: "SOURCE_DATA_TYPE"
                    Value: "double"
              - 
                SourceFields: 
                  - "Quantity"
                ConnectorOperator: 
                    Salesforce: "NO_OP"
                DestinationField: "Quantity"
                TaskType: "Map"
                TaskProperties: 
                  - 
                    Key: "DESTINATION_DATA_TYPE"
                    Value: "double"
                  - 
                    Key: "SOURCE_DATA_TYPE"
                    Value: "double"
              - 
                SourceFields: 
                  - "CurrencyIsoCode"
                ConnectorOperator: 
                    Salesforce: "NO_OP"
                DestinationField: "CurrencyIsoCode"
                TaskType: "Map"
                TaskProperties: 
                  - 
                    Key: "DESTINATION_DATA_TYPE"
                    Value: "picklist"
                  - 
                    Key: "SOURCE_DATA_TYPE"
                    Value: "picklist"
              - 
                SourceFields: 
                  - "UnitPrice"
                ConnectorOperator: 
                    Salesforce: "NO_OP"
                DestinationField: "UnitPrice"
                TaskType: "Map"
                TaskProperties: 
                  - 
                    Key: "DESTINATION_DATA_TYPE"
                    Value: "currency"
                  - 
                    Key: "SOURCE_DATA_TYPE"
                    Value: "currency"
              - 
                SourceFields: 
                  - "ListPrice"
                ConnectorOperator: 
                    Salesforce: "NO_OP"
                DestinationField: "ListPrice"
                TaskType: "Map"
                TaskProperties: 
                  - 
                    Key: "DESTINATION_DATA_TYPE"
                    Value: "currency"
                  - 
                    Key: "SOURCE_DATA_TYPE"
                    Value: "currency"
              - 
                SourceFields: 
                  - "TotalPrice"
                ConnectorOperator: 
                    Salesforce: "NO_OP"
                DestinationField: "TotalPrice"
                TaskType: "Map"
                TaskProperties: 
                  - 
                    Key: "DESTINATION_DATA_TYPE"
                    Value: "currency"
                  - 
                    Key: "SOURCE_DATA_TYPE"
                    Value: "currency"
              - 
                SourceFields: 
                  - "Description"
                ConnectorOperator: 
                    Salesforce: "NO_OP"
                DestinationField: "Description"
                TaskType: "Map"
                TaskProperties: 
                  - 
                    Key: "DESTINATION_DATA_TYPE"
                    Value: "string"
                  - 
                    Key: "SOURCE_DATA_TYPE"
                    Value: "string"
              - 
                SourceFields: 
                  - "CreatedDate"
                ConnectorOperator: 
                    Salesforce: "NO_OP"
                DestinationField: "CreatedDate"
                TaskType: "Map"
                TaskProperties: 
                  - 
                    Key: "DESTINATION_DATA_TYPE"
                    Value: "datetime"
                  - 
                    Key: "SOURCE_DATA_TYPE"
                    Value: "datetime"
              - 
                SourceFields: 
                  - "CreatedById"
                ConnectorOperator: 
                    Salesforce: "NO_OP"
                DestinationField: "CreatedById"
                TaskType: "Map"
                TaskProperties: 
                  - 
                    Key: "DESTINATION_DATA_TYPE"
                    Value: "reference"
                  - 
                    Key: "SOURCE_DATA_TYPE"
                    Value: "reference"
              - 
                SourceFields: 
                  - "LastModifiedDate"
                ConnectorOperator: 
                    Salesforce: "NO_OP"
                DestinationField: "LastModifiedDate"
                TaskType: "Map"
                TaskProperties: 
                  - 
                    Key: "DESTINATION_DATA_TYPE"
                    Value: "datetime"
                  - 
                    Key: "SOURCE_DATA_TYPE"
                    Value: "datetime"
              - 
                SourceFields: 
                  - "LastModifiedById"
                ConnectorOperator: 
                    Salesforce: "NO_OP"
                DestinationField: "LastModifiedById"
                TaskType: "Map"
                TaskProperties: 
                  - 
                    Key: "DESTINATION_DATA_TYPE"
                    Value: "reference"
                  - 
                    Key: "SOURCE_DATA_TYPE"
                    Value: "reference"
              - 
                SourceFields: 
                  - "SystemModstamp"
                ConnectorOperator: 
                    Salesforce: "NO_OP"
                DestinationField: "SystemModstamp"
                TaskType: "Map"
                TaskProperties: 
                  - 
                    Key: "DESTINATION_DATA_TYPE"
                    Value: "datetime"
                  - 
                    Key: "SOURCE_DATA_TYPE"
                    Value: "datetime"
              - 
                SourceFields: 
                  - "OrderItemNumber"
                ConnectorOperator: 
                    Salesforce: "NO_OP"
                DestinationField: "OrderItemNumber"
                TaskType: "Map"
                TaskProperties: 
                  - 
                    Key: "DESTINATION_DATA_TYPE"
                    Value: "string"
                  - 
                    Key: "SOURCE_DATA_TYPE"
                    Value: "string"
              - 
                